# Generated by Django 4.2.3 on 2023-08-06 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=255)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=2)),
                ('current', models.BooleanField(blank=True, default=True)),
                ('years', models.IntegerField(blank=True)),
                ('company', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pictures/')),
                ('user_type', models.CharField(choices=[('applicant', 'Applicant'), ('hr', 'HR')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
