# Generated by Django 4.2.3 on 2023-08-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_jobcategory_jobposting_noofrounds_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='years',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
