# Generated by Django 4.2.3 on 2023-08-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_userprofile_cgpa_alter_userprofile_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
