# Generated by Django 4.2.4 on 2023-08-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_userprofile_degree_userprofile_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='job_description',
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='package',
            field=models.CharField(default=1000, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.TextField(),
        ),
    ]
