# Generated by Django 4.2.4 on 2023-08-08 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_remove_jobposting_job_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='category',
        ),
        migrations.DeleteModel(
            name='JobCategory',
        ),
    ]
