# Generated by Django 4.2.4 on 2023-08-08 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_remove_jobposting_category_delete_jobcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='poster',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='data.userprofile'),
        ),
    ]
