# Generated by Django 4.2.4 on 2023-08-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_alter_jobposting_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='expected_cgpa',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
