# Generated by Django 4.2.4 on 2023-08-09 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_remove_jobapplication_qualified_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='qualified_round',
            field=models.CharField(choices=[('first', 'First Round'), ('second', 'Second Round'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='first', max_length=10),
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.PositiveIntegerField(default=0)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.jobposting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.userprofile')),
            ],
        ),
    ]
