# Generated by Django 4.2.4 on 2023-08-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_alter_jobapplication_qualified_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='description_enhance',
            field=models.TextField(default=None),
        ),
    ]
